import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={` min-h-screen bg-gradient-to-br from-[#F5FAFF] to-[#E8F4FD]`}>
      <main>
        {children}
      </main>
    </div>
  );
}
