import type { Metadata } from "next";

import { getSession } from "@/lib/getSession";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = session?.user;
  if (!user) return redirect("/sign-in");
  return (
    <div className={` min-h-screen bg-gradient-to-br from-[#F5FAFF] to-[#E8F4FD]`}>
    
      <main>
        {children}
      </main>
      
    </div>
  );
}
